# Generated by Django 5.2.12 on 2026-04-18 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery Photos'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('agriculture', 'Agriculture'), ('health', 'Health'), ('community', 'Community'), ('water', 'Water')], default='community', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
