# Generated by Django 5.2.12 on 2026-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0003_alter_galleryimage_options_remove_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short summary shown on the card (1–2 sentences).')),
                ('resource_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('research', 'Research Publication'), ('policy_brief', 'Policy Brief'), ('programme_update', 'Programme Update'), ('media_kit', 'Media Kit'), ('other', 'Other')], default='annual_report', max_length=30)),
                ('file', models.FileField(help_text='Upload PDF, DOCX, ZIP, or image.', upload_to='resources/%Y/')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover thumbnail.', upload_to='resources/covers/')),
                ('year', models.PositiveSmallIntegerField(help_text='Publication year e.g. 2024')),
                ('pages', models.PositiveSmallIntegerField(blank=True, help_text='Number of pages (optional)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the hero Latest Report at top of page')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the public page')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-year', 'order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='stat_label',
            field=models.CharField(max_length=60),
        ),
    ]
