# Generated by Django 5.2.12 on 2026-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0004_resource_delete_galleryimage_alter_partner_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank — auto-generated from title', max_length=240, unique=True)),
                ('category', models.CharField(choices=[('programmes', 'Programmes'), ('community', 'Community'), ('events', 'Events'), ('agriculture', 'Agriculture'), ('education', 'Education'), ('health', 'Health'), ('water', 'Clean Water'), ('partnerships', 'Partnerships'), ('announcements', 'Announcements')], default='announcements', max_length=30)),
                ('summary', models.CharField(help_text='One-sentence summary shown on cards (max 300 chars)', max_length=300)),
                ('body', models.TextField(help_text='Full article body. HTML is supported.')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image shown on card and article header', upload_to='news/covers/')),
                ('author', models.CharField(default='cosma development Team', max_length=120)),
                ('is_published', models.BooleanField(default=False, help_text='Check to make this article visible on the website')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to top of news feed as the featured story')),
                ('published_at', models.DateTimeField(blank=True, help_text="Leave blank to use today's date when publishing", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=120)),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('partner', 'Partner Organisation'), ('beneficiary', 'Beneficiary'), ('community', 'Community Member'), ('other', 'Other')], default='donor', max_length=20)),
                ('organisation', models.CharField(blank=True, help_text='Organisation or location (optional)', max_length=120)),
                ('body', models.TextField(help_text='The testimonial text — keep it to 2–4 sentences for best display.')),
                ('photo', models.ImageField(blank=True, help_text='Headshot (optional but recommended)', upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating 1–5')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials show on the website')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in the homepage featured row')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
