# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0005_newspost_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactstory',
            name='author',
            field=models.CharField(default='Webadmin', max_length=120),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='challenge',
            field=models.TextField(blank=True, help_text='What problem did this person, family, or community face?'),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='headline',
            field=models.CharField(blank=True, help_text='Short impact-story headline shown on cards.', max_length=180),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='intervention',
            field=models.TextField(blank=True, help_text='What did COSMA and partners provide?'),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='outcome',
            field=models.TextField(blank=True, help_text='What changed? Include concrete human results where possible.'),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='programme',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('child_sponsorship', 'Child Sponsorship'), ('vocational', 'Vocational & Life Skills'), ('education', 'Education'), ('health', 'Health'), ('water', 'Clean Water'), ('community', 'Community Development')], default='community', max_length=30),
        ),
        migrations.AddField(
            model_name='impactstory',
            name='quote',
            field=models.CharField(blank=True, help_text='Optional direct quote from the participant or family.', max_length=260),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('education', 'Education'), ('agriculture', 'Agriculture'), ('health', 'Health'), ('community', 'Community'), ('water', 'Water'), ('sponsorship', 'Child Sponsorship'), ('vocational', 'Vocational Training')], default='community', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
