# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0006_galleryimage_impactstory_programme_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('child_sponsorship', 'Child Sponsorship'), ('vocational', 'Vocational & Life Skills'), ('donations', 'Donations'), ('volunteering', 'Volunteering'), ('partnerships', 'Partnerships'), ('general', 'General')], default='general', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
