# Generated by Django 5.2.12 on 2026-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0008_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_Vision_CoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=255)),
                ('vision', models.CharField(max_length=255)),
                ('purpose', models.TextField(help_text='Write the purpose in 1–2 sentences')),
                ('core_values', models.TextField(help_text='Enter values separated by commas e.g. Integrity, Innovation, Community')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
