# Generated by Django 5.2.12 on 2026-04-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0009_mission_vision_corevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionVisionPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mission_Vision_CoreValues',
        ),
        migrations.AddField(
            model_name='corevalue',
            name='mission_vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='cosma_development.missionvisionpurpose'),
        ),
    ]
