# Generated by Django 5.2.12 on 2026-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0010_corevalue_missionvisionpurpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriApproachStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agriculture Approach Step',
                'verbose_name_plural': 'Agriculture Approach Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('our_story', 'Our Story'), ('team_partners', 'Team & Partners'), ('resources', 'Resources'), ('agri_why', 'Agriculture – Why'), ('agri_approach', 'Agriculture – Approach'), ('agri_support', 'Agriculture – Support a Farmer'), ('agri_impact', 'Agriculture – Impact Stories'), ('agri_faqs', 'Agriculture – FAQs'), ('sponsor_why', 'Sponsorship – Why'), ('sponsor_child', 'Sponsorship – Sponsor a Child'), ('vocational', 'Vocational & Life Skills'), ('sponsorship_impact', 'Sponsorship – Impact Stories'), ('sponsorship_faqs', 'Sponsorship – FAQs'), ('impact_numbers', 'Impact in Numbers'), ('impact_stories', 'Impact Stories'), ('gallery', 'Gallery'), ('partner_with_us', 'Partner With Us'), ('volunteer', 'Volunteer'), ('share_story', 'Share Our Story'), ('signup_updates', 'Sign Up for Updates'), ('news', 'News & Updates'), ('contact', 'Contact'), ('donate', 'Donate'), ('faqs', 'FAQs')], max_length=40, unique=True)),
                ('tag_text', models.CharField(blank=True, help_text='Small pill label above the heading', max_length=80)),
                ('tag_icon', models.CharField(blank=True, default='bi-stars', help_text='Bootstrap icon class e.g. bi-globe-africa', max_length=40)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.TextField(blank=True, help_text='Paragraph text below the heading')),
                ('image', models.ImageField(blank=True, help_text='Upload a hero image (recommended ≥1800×900px)', upload_to='heroes/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL')),
                ('overlay_opacity', models.FloatField(default=0.55, help_text='Dark overlay strength 0 (none) → 1 (full black). Default 0.55')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('raw', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Our-Story Hero Stat',
                'verbose_name_plural': 'Our-Story Hero Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='home_slides/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Slide',
                'verbose_name_plural': 'Home Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Display value e.g. "125,000+" or "98%"', max_length=20)),
                ('raw', models.PositiveIntegerField(help_text='Numeric value for the counter animation')),
                ('suffix', models.CharField(blank=True, help_text='Appended to the counter e.g. "+"', max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Stat',
                'verbose_name_plural': 'Home Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactBigStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(default='bi-people-fill', max_length=50)),
                ('color', models.CharField(default='#8E0005', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact Big Stat',
                'verbose_name_plural': 'Impact Big Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('figure', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact Item (Donate)',
                'verbose_name_plural': 'Impact Items (Donate)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactProgrammeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=30)),
                ('pct', models.PositiveSmallIntegerField(help_text='Bar width % 0–100')),
                ('color', models.CharField(default='#3BAD6E', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact Programme Stat',
                'verbose_name_plural': 'Impact Programme Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrgGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Percentage 0–100')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Organisation Goal',
                'verbose_name_plural': 'Organisation Goals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='bi-building', max_length=50)),
                ('color', models.CharField(default='#8E0005', max_length=20)),
                ('bg', models.CharField(default='rgba(142,0,5,.1)', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partnership Type',
                'verbose_name_plural': 'Partnership Types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.CharField(default='Plot 45, Kampala Road, Kampala, Uganda', max_length=255)),
                ('phone', models.CharField(default='+256 700 123 456', max_length=50)),
                ('email', models.EmailField(default='info@cosmadevelopments.org', max_length=254)),
                ('office_hours', models.CharField(default='Mon–Fri: 8am – 5pm | Sat: 9am – 1pm', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('globalgiving_url', models.URLField(default='https://www.globalgiving.org/donate/11831/cosma-sustainable-rural-development/')),
                ('footer_tagline', models.CharField(default='Building resilient communities across Uganda through education, health, livelihoods, and clean water since 2006.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SponsorStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sponsor-a-Child Step',
                'verbose_name_plural': 'Sponsor-a-Child Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. "2006" or "Today"', max_length=10)),
                ('icon', models.CharField(default='bi-star', help_text='Bootstrap icon class e.g. bi-house-heart', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('stat', models.CharField(blank=True, help_text='Optional statistic pill e.g. "42 children in Year 1"', max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='timeline/')),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VocationalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='bi-tools', help_text='Bootstrap icon class', max_length=50)),
                ('duration', models.CharField(help_text='e.g. "3 Months"', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vocational Course',
                'verbose_name_plural': 'Vocational Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('icon', models.CharField(default='bi-person-heart', max_length=50)),
                ('color', models.CharField(default='#3BAD6E', max_length=20)),
                ('bg', models.CharField(default='rgba(59,173,110,.1)', max_length=40)),
                ('commitment', models.CharField(help_text='e.g. "Min. 1 month"', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Volunteer Role',
                'verbose_name_plural': 'Volunteer Roles',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='missionvisionpurpose',
            options={'verbose_name': 'Mission, Vision & Purpose', 'verbose_name_plural': 'Mission, Vision & Purpose'},
        ),
        migrations.AddField(
            model_name='corevalue',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class e.g. bi-shield-check', max_length=50),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionvisionpurpose',
            name='goal',
            field=models.TextField(blank=True, help_text='Organisation goal statement shown beneath Mission & Vision'),
        ),
        migrations.AddField(
            model_name='missionvisionpurpose',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='headline',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='intervention',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='quote',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(help_text='Full article body. HTML supported.'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='news/covers/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='summary',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.CharField(choices=[('bi-book-half', 'Book'), ('bi-heart-pulse', 'Heart Pulse'), ('bi-briefcase', 'Briefcase'), ('bi-droplet-half', 'Droplet'), ('bi-house-heart', 'House Heart'), ('bi-people-fill', 'People'), ('bi-flower1', 'Flower'), ('bi-tools', 'Tools')], default='bi-book-half', max_length=40),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='resources/covers/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/%Y/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='organisation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
