# Generated by Django 5.2.12 on 2026-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosma_development', '0011_agriapproachstep_herosection_herostat_homeslide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactstory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us — Who We Are'), ('our_approach', 'About Us — Our Approach'), ('our_story', 'Our Story'), ('team_partners', 'Team & Partners'), ('resources', 'Resources'), ('agri_why', 'Agriculture – Why Agriculture'), ('agri_approach', 'Agriculture – Our Approach'), ('agri_support', 'Agriculture – Support a Farmer'), ('agri_impact', 'Agriculture – Impact Stories'), ('agri_faqs', 'Agriculture – FAQs'), ('sponsor_why', 'Sponsorship – Why Sponsorship'), ('sponsor_child', 'Sponsorship – Sponsor a Child'), ('vocational', 'Sponsorship – Vocational & Life Skills'), ('sponsorship_impact', 'Sponsorship – Impact Stories'), ('sponsorship_faqs', 'Sponsorship – FAQs'), ('impact_numbers', 'Impact in Numbers'), ('impact_stories', 'Impact Stories'), ('gallery', 'Gallery'), ('partner_with_us', 'Partner With Us'), ('volunteer', 'Volunteer With Us'), ('fund_project', 'Fund a Project — Wishlist'), ('share_story', 'Share Our Story'), ('signup_updates', 'Sign Up for Updates'), ('news', 'News & Updates'), ('contact', 'Contact'), ('donate', 'Donate'), ('faqs', 'FAQs')], max_length=40, unique=True),
        ),
    ]
